admin = true
bridges = []
persistence_dir = "./tmp/persistence-deepkey"

[[agents]]
 id = "test_agent1"
 name = "Agent 1"
 public_address = "HcSCJbpm8CZparb6f5iEKKRv4Te4op93q6ESMRuDtwp9abbzV8zYTF7EKqqw9ei"
 keystore_file = "./agent1.keystore"

[[agents]]
  id = "test_agent2"
  name = "Agent 2"
  public_address = "HcSciScdx7wkdeuft7qmvRnYx53rk9nbayCK7IS9JA6s8sxr6qBOWb3KpO5vypi"
  keystore_file = "/home/lisa/.config/holochain/keys/HcSciScdx7wkdeuft7qmvRnYx53rk9nbayCK7IS9JA6s8sxr6qBOWb3KpO5vypi"

[[dnas]]
  id = "personas_profiles"
  file = "/home/lisa/Documents/gitrepos/holochain/personas-profiles/personas-profiles/dna-src/dist/dna-src.dna.json"
  hash = "QmQtY4pKFS4j9y9Hh9WnBHezgy4P5QrzbbARubpLcoD5sE"

[[dnas]]
  id = "deepkey"
  file = "/home/lisa/Documents/gitrepos/holochain/deepKey/DeepKey/dist/DeepKey.dna.json"
  # file = "/deepKey-dna/dist/DeepKey.dna.json"
  hash = "QmWziNHrDrNhXvDrRHjo1pUHPojk6YYsvYZXAxZLv3x12o"

[[instances]]
 id = "personas-profiles"
 dna = "personas_profiles"
 agent = "test_agent2"
[instances.logger]
 type = "simple"
 file = "app_spec.log"
[instances.storage]
 type = "memory"
 path = "tmp-storage"

[[instances]]
  id = "dpki_happ"
  dna = "deepkey"
  agent = "test_agent2"
[instances.logger]
  type = "simple"
  file = "app_spec.log"
[instances.storage]
  type = "memory"
  path = "tmp-storage"

[[interfaces]]
  id = "websocket_interface"
[interfaces.driver]
  type = "websocket"
  port = 5401

[[interfaces.instances]]
 id = "personas-profiles"

[[interfaces.instances]]
 id = "dpki_happ"

[dpki]
  instance_id = "dpki_happ"
  init_params = "{\"revocation_key\": \"HcScIXuxtWI6ttc5gngvQTsDnHtynb5dzyDujh37mNo43nf7ZRB5UZKmR9953pa\"}"
